# Generated by Django 4.1.4 on 2023-02-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('tipologia', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('inversion', models.CharField(max_length=200)),
                ('fecha_presentacion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
    ]
